GET http://localhost:8000/api/dishes HTTP/1.1
###

POST http://localhost:8000/api/dishes HTTP/1.1
Content-Type: application/json

{
    "name": "Roast Pheasant"
}
###

GET http://localhost:8000/api/dishes/2 HTTP/1.1
###

//** Recipes


GET http://localhost:8000/api/recipes HTTP/1.1
###

POST http://localhost:8000/api/recipes HTTP/1.1
Content-Type: application/json

{
    "name": "Chicago pizza",
    "dish_id": 2
}
###

GET http://localhost:8000/api/recipes/2 HTTP/1.1

###
